name: Deploy Node.js App to AWS EC2

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  deploy:
    name: Deploy Node.js app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Copy Node.js code to EC2 using rsync
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            ./ ubuntu@13.232.124.239:/home/ubuntu/node-app

      - name: Install dependencies and restart app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@13.232.124.239 << 'EOF'
            cd /home/ubuntu/node-app
            npm install
            pm2 restart app || pm2 start app.js --name app
          EOF
