name: Deploy Node.js App to AWS

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Copy Node.js code to EC2
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            ./ ubuntu@3.108.65.38:/home/ubuntu/node-app

      - name: Restart Node.js app via SSH
        run: |
          ssh ubuntu@3.108.65.38 << 'EOF'
            cd /home/ubuntu/node-app
            npm install
            pm2 restart app || pm2 start app.js --name app
          EOF
